import type { RegionKernel } from "../types.js";

export const canopyKernel: RegionKernel = {
  id: "kernel:canopy",
  displayName: "The Canopy",
  lexiconRoots: ["leaf-", "bough-", "root-", "moss-", "bark-", "thicket-", "grove-", "sap-", "marsh-"],
  boundaryRoots: ["marsh-", "root-"], // shared with Fen and Hollow
  economicAxis: "mixed",
  puzzleAffinity: "growth-lock",
  arcPool: ["canopy:sap-plague", "canopy:sky-court"],
  biomeTag: "common",
  blend: { dominantTexture: "loam", accentTexture: "root-mat", paletteAnchor: 0.55 },
  settlementNamePool: [
    "Leafhome",
    "Boughwick",
    "Rootmere",
    "Mossgate",
    "Barkhollow",
    "Thicketstead",
    "Grovehaven",
    "Sapwell",
    "Canopy's Rest",
    "Boughcross",
    "Leaffall",
    "Mossbrook",
  ],
  npcNamePool: [
    "Wrenna Leafhand",
    "Osric Bough",
    "Talia Moss",
    "Fenwick Bark",
    "Sorrel Thicket",
    "Ambrose Grove",
    "Nell Sapwright",
    "Corin Leafborn",
    "Ysbel Root",
    "Garrick Mossward",
    "Elowen Bough",
    "Tam Barkwright",
  ],
  factionNamePool: [
    "The Grovewarden Circle",
    "Canopy Compact",
    "Boughwick Trading Co.",
    "The Sap Council",
    "Mossgate Freeholders",
  ],
  landmarkNamePool: [
    "The Elderbough",
    "Mossgate Hollow",
    "The Sapwell Spring",
    "Thicketstead Crossing",
    "The Grovehaven Canopy",
    "Barkhollow Rise",
    "The Leaf Cathedral",
    "Rootmere Basin",
    "The Sky Walk",
    "Boughwick Overlook",
    "The Sunken Grove",
    "Mossbrook Ford",
  ],
};
