import type { RegionKernel } from "../types.js";

export const cinderreachKernel: RegionKernel = {
  id: "kernel:cinderreach",
  displayName: "Cinderreach",
  lexiconRoots: ["cinder-", "forge-", "slag-", "ash-", "ember-", "kiln-", "soot-", "brand-"],
  boundaryRoots: ["ash-", "soot-"], // shared with Hollow
  economicAxis: "refining",
  puzzleAffinity: "heat-lock",
  arcPool: ["cinder:guild-rivalry", "cinder:collapsed-forge"],
  settlementNamePool: [
    "Cinderfall",
    "Forgehold",
    "Slagmere",
    "Ashcross",
    "Emberwatch",
    "Kilnstead",
    "Sootgate",
    "Brandmoor",
    "Cinderreach Prime",
    "Forgeward",
    "Ashenhall",
    "Kilnbrook",
  ],
  npcNamePool: [
    "Dara Forgehand",
    "Ossian Slag",
    "Rennik Ash",
    "Tovin Ember",
    "Marra Kiln",
    "Ustan Soot",
    "Delia Brand",
    "Cormac Cinder",
    "Ines Forgewright",
    "Talon Ashmark",
    "Wrenna Kilnwright",
    "Bastian Slagborn",
  ],
  factionNamePool: [
    "The Forgewright Guild",
    "Cinder Compact",
    "Ashmark Freeholders",
    "The Kiln Watch",
    "Slaghand Cartel",
  ],
  landmarkNamePool: [
    "The Great Kiln",
    "Slagfall Terrace",
    "The Ember Gate",
    "Sootspire",
    "The Brandmark Anvil",
    "Cinderreach Overlook",
    "The Ashen Stair",
    "Forgehollow Vent",
    "The Kilnward Wall",
    "Slag Row",
    "The Cindering",
    "Ashfall Ridge",
  ],
};
