import type { RegionKernel } from "../types.js";

/** The worked example from the design doc. */
export const fenKernel: RegionKernel = {
  id: "kernel:fen",
  displayName: "The Fen",
  lexiconRoots: ["salt-", "brine-", "tide-", "net-", "weir-", "silt-", "marsh-", "drown-"],
  boundaryRoots: ["silt-", "marsh-"], // shared with Hollow (silty caverns) and Canopy (marsh-forest edge)
  economicAxis: "extractive",
  puzzleAffinity: "tide-lock",
  arcPool: ["fen:smuggler-network", "fen:drowned-shrine"],
  settlementNamePool: [
    "Saltmere",
    "Tideford",
    "Weirhaven",
    "Brinewick",
    "Netstead",
    "Marshgate",
    "Siltmoor",
    "Drownhollow",
    "Weftide",
    "Fenwick",
    "Tarnmoor",
    "Reedcross",
  ],
  npcNamePool: [
    "Mera Salthand",
    "Coric Netmaker",
    "Wick Tidewell",
    "Ansa Weirborn",
    "Brona Marrow",
    "Iden Silt",
    "Sela Brine",
    "Tomas Drown",
    "Ysolde Fen",
    "Perrin Tarn",
    "Cass Marlow",
    "Odrin Reed",
  ],
  factionNamePool: [
    "The Weir Compact",
    "Saltmarsh Wardens",
    "Tideford Trading Co.",
    "The Drowned Hand",
    "Net & Tally Guild",
  ],
  landmarkNamePool: [
    "The Sunken Bell",
    "Old Weir Bridge",
    "Saltglass Shoals",
    "The Brinewatch",
    "Marrow Reef",
    "The Long Silt",
    "Weirstone Causeway",
    "The Drowned Orchard",
    "Tideglass Spit",
    "The Netting Grounds",
    "Fenlight Cairn",
    "The Salt Road's End",
  ],
};
