import type { RegionKernel } from "../types.js";

export const hollowKernel: RegionKernel = {
  id: "kernel:hollow",
  displayName: "The Hollow",
  lexiconRoots: ["deep-", "hollow-", "stone-", "echo-", "vein-", "dark-", "root-", "gloam-", "silt-", "soot-"],
  boundaryRoots: ["silt-", "soot-"], // shared with Fen and Cinderreach
  economicAxis: "extractive",
  puzzleAffinity: "resonance-lock",
  arcPool: ["hollow:cave-in", "hollow:lightless-cult"],
  settlementNamePool: [
    "Deepwell",
    "Hollowreach",
    "Stonegate",
    "Echomere",
    "Veinhold",
    "Darkbottom",
    "Gloamstead",
    "Rootcavern",
    "Hollowmark",
    "Deepvein",
    "Stonewick",
    "Echofall",
  ],
  npcNamePool: [
    "Brael Deepwell",
    "Nyra Stonehand",
    "Corwin Echo",
    "Adelys Vein",
    "Torin Gloam",
    "Sael Hollow",
    "Marek Root",
    "Ilva Darkbottom",
    "Renn Stonewright",
    "Fira Veinborn",
    "Josef Echomark",
    "Petra Deep",
  ],
  factionNamePool: [
    "The Deepwell Miners' Guild",
    "Hollow Watch",
    "Veinhold Compact",
    "The Gloam Chorus",
    "Stonegate Cartel",
  ],
  landmarkNamePool: [
    "The Echoing Stair",
    "Veinhold Chasm",
    "The Gloamlight Well",
    "Deepwell Shaft",
    "The Rootcavern Maw",
    "Stonegate Threshold",
    "The Silent Vein",
    "Hollowreach Deep",
    "The Dark Concourse",
    "Echofall Grotto",
    "The Buried Stair",
    "Gloamstead Hollow",
  ],
};
